### ISSUE TITLE
confused

### ISSUE THREAD

**Issue by MCjorsh5** [lachlan2k/DNSmuggle#4]
sorry to open another one, I've been a bit confused I want I would really like to run this project, but it's a bit confusing.

On my server I have a domain where it asks for it and I also have my NS a question the wireguard server should run locally also 127.0.0.1, or just listen to the IP it should work?

Sever run>

ip my server 157.90.156.136

./server -listenAddr 0.0.0.0:53 -domain turf.0i09uy89o.cf -psk hunter2 --nameserver ds.0i09uy89o.cf

2022/10/19 04:14:46 Starting tunnel server (turf.0i09uy89o.cf.) on 0.0.0.0:53

wireguard server 157.90.156.136 port 51280

The client ran it as the example 
./client -dialAddr 10.1.1.1:51820 -domain turf.0i09uy89o.cf -psk hunter2 -resolver 1.1.1.1:53 -listenAddr 127.0.0.1:51280

I still don't understand about dialaddr, was it listening or is it not necessary to change and it always has to listen to the wireguard port itself? Or I can use this to change the tunnel port Listening for wireguard client?The point of my client wireguard is located On 127.0.0.1 port 51280 

I have not achieved anything and everything seems correct

**Comment by lachlan2k** [comment]
Hi,

`-dialAddr` should be the location of your remote wireguard server. The dnsmuggle client instructs the dnsmuggle server which wireguard server it wants to connect to.

For example, perhaps `-dialAddr 157.90.156.136:51280` would be suitable for you? If you are running DNSmuggle on the same server as wireguard, then `-dialAddr 127.0.0.1:51280` might also work.

Does this make sense? This diagram might help (example where `dialAddr` is 10.1.1.12):

![image](https://user-images.githubusercontent.com/4683714/196614881-e2f95976-3b95-411f-bd21-b6419b164c46.png)


Also, can you please show me your DNS configuration? I would like to check there are no mistakes there.

**Comment by MCjorsh5** [comment]
![IMG_20221019_004638](https://user-images.githubusercontent.com/37552072/196616776-8ba4d18b-5ee9-4754-b69a-2df2054fec60.jpg)

**Comment by MCjorsh5** [comment]
i am running wireguard on the same server so this should work?


./client -dialAddr 127.0.0.1:51820 -domain turf.0i09uy89o.cf -psk hunter2 -resolver 1.1.1.1:53 -listenAddr 127.0.0.1:51280

**Comment by testingnic** [comment]
![IMG_20221019_011053_085](https://user-images.githubusercontent.com/37552072/196621449-92ee8270-aef7-486a-a927-4a3ebfdf05fc.png)


Server settings

**Comment by MCjorsh5** [comment]
Is this type of tunnel that I have developed a fast connection tunnel or is it slow because it makes dns queries? Or is it a type of fast normal speed?

**Comment by lachlan2k** [comment]
I think your configuration should work, but your domains are the wrong way around. Use `-domain ds.0i09uy89o.cf` on the client, and  `-domain ds.0i09uy89o.cf -nameserver turf.0i09uy89o.cf` on the server.

`turf` is the authoritative nameserver of `ds` in your config. The NS record says "Hey, when you want to resolve something on `ds`, you should ask `turf`", hence why `turf` then has an A record to your server.

The tunnel speed will vary, depending on the speed of DNS server, network latency, rate limiting, etc. I plan on adding a round-robin resolver list at some point to help with this.

FYI: deleted screenshot due to key leakage.

**Comment by MCjorsh5** [comment]
I thought I needed A, I thought it was normal domain but now I understand it will always have to be NS

**Comment by MCjorsh5** [comment]
One question -domains can I use my own server NS or can it be any or specific to the ISP to bypass or does it always have to be from my same server?

**Comment by MCjorsh5** [comment]
![IMG_20221019_085327](https://user-images.githubusercontent.com/37552072/196726989-d525803b-17f6-45f5-8949-1558b9f6c4e1.jpg)

here I made a better domain to make it understandable, can you tell me how it should be configured correctly with these following values ​​and example 

Domains DNS A Origin: atunnel.dnstunnel.ml
NS1: ns1.dnstunnel.ml
NS2: ns2sv.dnstunnel.ml

My wireguard client is this 

![IMG_20221019_085804](https://user-images.githubusercontent.com/37552072/196727668-a78f1fdb-23bd-4170-9454-04f46ed310cf.jpg)

**Comment by MCjorsh5** [comment]
Bro

**Comment by MCjorsh5** [comment]
@lachlan2k 

It seems that I already managed to make the connection but I get the following error

![remmina_Quick Connect_45 77 150 66_20221020-163100](https://user-images.githubusercontent.com/37552072/197006573-01f1ea93-c827-45a0-acbe-dec04678cb98.png)

This is my domain configuration currently.

![screen2](https://user-images.githubusercontent.com/37552072/197007289-46c37acd-5b4a-4cc5-a1b3-3cb4af86eaa8.jpg)

Now what is the problem

**Comment by lachlan2k** [comment]
Hi,

Please try rolling back to commit 1538f4fef9da3884016769df9db6d2b53cf7df09, it is the last version I extensively tested. The head of main is likely unstable.

**Comment by MCjorsh5** [comment]
2022/10/20 20:34:58 Starting tunnel server (ns1.dnstunnel-udp.tk.) on 0.0.0.0:53
2022/10/20 20:36:44 Received new session request
2022/10/20 20:36:44 Handling error for 01K4UU9SEOHB23GESLPIKOGDL3FO3HI76T2CH16GCM6T6AMQ0GPBR4EKEGB9P3H.MV3N6M6QVRT3JIM1AIQO46I54IINH3HLAO9ISLPOU.: lookup ���127.0.0.1: no such host

**Comment by lachlan2k** [comment]
Can you show me the exact arguments you are using for both the server and the client?

And please make sure the client is compiled from the same version as the server.

**Comment by MCjorsh5** [comment]
![IMG_20221020_150950](https://user-images.githubusercontent.com/37552072/197058749-0340171e-6ad7-4f63-9694-a6ad736b75af.jpg)



![IMG_20221020_150909_226](https://user-images.githubusercontent.com/37552072/197058774-0514c39a-1417-47d7-a009-96fe73510b93.jpg)

**Comment by MCjorsh5** [comment]
now this client and server same version appears to me, but there is no internet traffic 
In the photos above is the configuration of my DNS domain, am I correct? What would be the correct client and server command to work with me

**Comment by MCjorsh5** [comment]
@lachlan2k bro? Help me

**Comment by MCjorsh5** [comment]
@lachlan2k help me bro

**Comment by NHAS** [comment]
@testingnic frankly an open source maintainer has no obligation to offer technical support to anyone and you are lucky to have gotten the support thats been provided so far. 

I dont expect being rude and constantly bugging this maintainer is going to do anything more than bug everyone involved.
